"""
========================================
 NIFTY Guardian Signal Model
========================================
"""

from dataclasses import dataclass, field


@dataclass
class Signal:
    """
    Final decision generated by the strategy engine.
    """

    action: str
    confidence: int

    reasons: list[str] = field(default_factory=list)

    entry: float = 0.0
    stop_loss: float = 0.0

    target1: float = 0.0
    target2: float = 0.0

    market_bias: str = "Neutral"

    strategy_version: str = "2.0"

    timestamp: str = ""

    remarks: str = ""